
/*
This file was generated by cbintxt at 15:20:35 on 2024-12-6.
cbintxt is freely available at https://github.com/chickenspaceprogram/cbintxt under the Mozilla Public License Version 2.0.
*/

#ifndef CBINTXT_HELP_H
#define CBINTXT_HELP_H

#include <stdio.h>

void help(FILE *stream);

#endif
