
/*
This file was generated by cbintxt at 15:20:35 on 2024-12-6.
cbintxt is freely available at https://github.com/chickenspaceprogram/cbintxt under the Mozilla Public License Version 2.0.
*/

#include "help.h"

void help(FILE *stream) {
    fputs
    (
    "cbintxt v0.2\n"
    "\n"
    "Usage: cbintxt <output> <input> [-n <name>] ...\n"
    "\n"
    "<output> ::= The filename of the output, without a file extension.\n"
    "<input> ::= The filename(s) of the input text file. Pass `-` to read from stdin.\n"
    "\n"
    "Flags:\n"
    "\n"
    "-n <name>: Specifies a function name that differs from the file\'s name. Mandatory if reading from stdin.\n"
    " \n"
    ""
    , stream
    );
}
