#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "tokenize.h"

#include "file-handling.h"

FILE **open_files(int argc, char **argv, int *num_input_files) {
    if (argc == 2) {
        *num_input_files = 1;
    }
    else {
        *num_input_files = argc - 2;
    }

    FILE **in = malloc(sizeof(FILE *) * (*num_input_files));
    if (in == NULL) {
        fprintf(stderr, "Error: could not allocate memory. Try running the program again.\n");
        return NULL;
    }

    if (argc == 1) {
        in[0] = stdin;
        return in;
    }

    for (int i = 2, current_file = 0; i < argc; ++i) {
        if (open_input_file(in, current_file, argv[i]) == NULL) {
            free(in);
            fprintf(stderr, "Error: could not open input file `%s`.\n", argv[i]);
            return NULL;
        }

        ++current_file;
    }
    return in;
}

FILE *open_input_file(FILE **files, int file_index, char *name) {
    files[file_index] = fopen(name, "r");
    if (files[file_index] == NULL && file_index != 0) {
        close_files(files, file_index);
    }
    return files[file_index];
}

bool set_output_filenames(char **out_h, char **out_c, char *name) {
    int out_name_len = strlen(name) + 2;
    *out_h = malloc(sizeof(char) * (out_name_len + 1));
    *out_c = malloc(sizeof(char) * (out_name_len + 1));

    if (*out_h == NULL || *out_c == NULL) {
        if (*out_h != NULL) {
            free(*out_h);
            *out_h = NULL;
        }
        if (*out_c != NULL) {
            free(*out_c);
            *out_c = NULL;
        }
        return false;
    }

    for (int i = 0; i < out_name_len + 1; ++i) {
        (*out_h)[i] = '\0';
        (*out_c)[i] = '\0';
    }

    strcpy(*out_h, name);
    strcpy(*out_c, name);
    
    strcpy((*out_h) + (sizeof(char) * (out_name_len - 2)), ".h");
    strcpy((*out_c) + (sizeof(char) * (out_name_len - 2)), ".c");
    return true;
}

bool open_output_files(FILE **out_h, FILE **out_c, char *out_name_h, char *out_name_c) {
    *out_h = fopen(out_name_h, "w");
    *out_c = fopen(out_name_c, "w");
    if (out_h == NULL || out_c == NULL) {
        if (out_h == NULL) {
            fprintf(stderr, "Error: file %s could not be opened for writing.\n", out_name_h);
        }
        else {
            fclose(*out_h);
            *out_h = NULL;
        }
        if (out_c == NULL) {
            fprintf(stderr, "Error: file %s could not be opened for writing.\n", out_name_c);
        }
        else {
            fclose(*out_h);
            *out_h = NULL;
        }
        return false;
    }
    return true;
}

void close_files(FILE **files, int num_files) {
    for (int i = 0; i < num_files; ++i) {
        fclose(files[i]);
    }
}

void put_name_caps(FILE *out, char *name) {
    for (int i = 0; name[i] != '\0'; ++i) {
        if (isalpha(name[i])) {
            fputc(name[i] - 'a' + 'A', out);
        }
        else {
            fputc(name[i], out);
        }
    }
}

void print_date(FILE *out) {
    time_t unix_time = time(NULL);
    struct tm *current_time = localtime(&unix_time);
    fprintf(out, "%d-%d-%d", current_time->tm_year + 1900, current_time->tm_mon + 1, current_time->tm_mday);
}

void print_time(FILE *out) {
    time_t unix_time = time(NULL);
    struct tm *current_time = localtime(&unix_time);
    fprintf(out, "%02d:%02d:%02d", current_time->tm_hour, current_time->tm_min, current_time->tm_sec);
}

void print_comment(FILE *out) {
    fputs("\n/*\nThis file was generated by cbintxt at ", out);
    print_time(out);
    fputs(" on ", out);
    print_date(out);
    fputs(".\ncbintxt is freely available at https://github.com/chickenspaceprogram/cbintxt under the Mozilla Public License Version 2.0.\n*/\n\n", out);
}

void print_header_file(FILE *out, char *name) {
    print_comment(out);

    fputs("#ifndef CBINTXT_", out);
    put_name_caps(out, name);
    fputs("_H\n#define CBINTXT_", out);
    put_name_caps(out, name);
    fputs("_H\n\n", out);

    fputs("#include <stdio.h>\n\n", out);

    fprintf(out, "void %s(FILE *stream);\n\n", name);
    fputs("#endif\n", out);
}

void print_c_file(FILE *out, FILE **in, char *name, int num_inputs) {
    print_comment(out);

    fprintf(out, "#include \"%s.h\"\n\nvoid %s(FILE *stream) {\n    fputs\n    (\n    ", name, name);
    for (int i = 0; i < num_inputs; ++i) {
        esc_replace(out, in[i]);
    }
    fputs("    , stream\n    );\n}\n", out);
}